services:
  pi-demo-app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped